# Generated by Django 4.0.4 on 2022-05-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('Муж', 'Муж'), ('Жен', 'Жен'), ('Хто я...', 'Хто я...')], default='Хто я...', max_length=50, verbose_name='Пол'),
        ),
    ]
