# Generated by Django 4.0.4 on 2022-05-29 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeType',
            fields=[
                ('anime_type', models.CharField(choices=[('film', 'фильм'), ('series', 'сериал'), ('spec', 'спешл'), ('clip', 'клип'), ('ova', 'ova'), ('ona', 'ona')], max_length=6, primary_key=True, serialize=False, verbose_name='Тип')),
            ],
            options={
                'ordering': ['-anime_type'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre', models.CharField(choices=[('senen', 'сёнен'), ('senen-ai', 'сёнен-ай'), ('seinen', 'сэйнен'), ('shojo', 'сёдзё'), ('shojo-ai', 'сёдзё-ай'), ('dzesei', 'дзёсей'), ('comedy', 'комедия'), ('romance', 'романтика'), ('school', 'школа'), ('madness', 'безумие'), ('martial_arts', 'боевые искусства'), ('vampires', 'вампиры'), ('war', 'военное'), ('harem', 'гарем'), ('gourmet', 'гурман'), ('demons', 'демоны'), ('detective', 'детектив'), ('baby', 'детское'), ('drama', 'драма'), ('historical', 'исторический'), ('space', 'космос'), ('games', 'игры'), ('magic', 'магия'), ('cars', 'машины'), ('furs', 'меха'), ('music', 'музыка'), ('parody', 'пародия'), ('everyday life', 'повседневность'), ('police', 'полиция'), ('adventure', 'приключение'), ('psychological', 'психологическое'), ('work', 'работа'), ('samurai', 'самураи'), ('supernatural', 'сверхъестественное'), ('sport', 'спорт'), ('super power', 'супер сила'), ('horrors', 'ужасы'), ('fantastic', 'фантастика'), ('fantasy', 'фэнтези'), ('action', 'экшен'), ('etty', 'этти'), ('thriller', 'триллер')], default=('senen', 'сёнен'), max_length=13, primary_key=True, serialize=False, verbose_name='Категория')),
            ],
            options={
                'ordering': ['-genre'],
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('status', models.CharField(choices=[('announced', 'анонсированно'), ('coming', 'выходит'), ('ready', 'вышло'), ('pause', 'приостановленно'), ('error', 'отменено')], default='announced', max_length=9, verbose_name='Статус')),
                ('rating', models.PositiveSmallIntegerField(choices=[(None, 'Пока не оценено'), (1, 'Мои Глаза'), (2, 'Жалко потраченного времени'), (3, 'Проект на один раз'), (4, 'Хороий проект'), (5, 'Проект нашел отклик в моей душе')], default=None, verbose_name='Рэйтинг')),
                ('about', models.TextField(verbose_name='Описание')),
                ('trailer', models.FileField(blank=True, null=True, upload_to='', verbose_name='Трейлер')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Заглавная картинка')),
                ('links', models.TextField(blank=True, null=True, verbose_name='Ссылки на источники для просмотра аниме')),
                ('genre', models.ManyToManyField(to='anime.genre', verbose_name='Жанр')),
                ('typeAnime', models.ForeignKey(default='film', on_delete=django.db.models.deletion.CASCADE, to='anime.animetype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Аниме',
                'verbose_name_plural': 'Аниме',
            },
        ),
    ]
