# Generated by Django 4.0.4 on 2022-05-29 08:09

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_alter_anime_typeanime_alter_genre_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='genre',
        ),
        migrations.AddField(
            model_name='anime',
            name='genre',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('senen', 'сёнен'), ('senen-ai', 'сёнен-ай'), ('seinen', 'сэйнен'), ('shojo', 'сёдзё'), ('shojo-ai', 'сёдзё-ай'), ('dzesei', 'дзёсей'), ('comedy', 'комедия'), ('romance', 'романтика'), ('school', 'школа'), ('madness', 'безумие'), ('martial_arts', 'боевые искусства'), ('vampires', 'вампиры'), ('war', 'военное'), ('harem', 'гарем'), ('gourmet', 'гурман'), ('demons', 'демоны'), ('detective', 'детектив'), ('baby', 'детское'), ('drama', 'драма'), ('historical', 'исторический'), ('space', 'космос'), ('games', 'игры'), ('magic', 'магия'), ('cars', 'машины'), ('furs', 'меха'), ('music', 'музыка'), ('parody', 'пародия'), ('everyday life', 'повседневность'), ('police', 'полиция'), ('adventure', 'приключение'), ('psychological', 'психологическое'), ('work', 'работа'), ('samurai', 'самураи'), ('supernatural', 'сверхъестественное'), ('sport', 'спорт'), ('super power', 'супер сила'), ('horrors', 'ужасы'), ('fantastic', 'фантастика'), ('fantasy', 'фэнтези'), ('action', 'экшен'), ('etty', 'этти'), ('thriller', 'триллер')], max_length=329, null=True, verbose_name='Жанр'),
        ),
    ]
