# Generated by Django 4.0.4 on 2022-05-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_remove_anime_genre_anime_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Пока не оценено'), (1, 'Мои Глаза'), (2, 'Жалко потраченного времени'), (3, 'Проект на один раз'), (4, 'Хороий проект'), (5, 'Проект нашел отклик в моей душе')], default=None, null=True, verbose_name='Рэйтинг'),
        ),
    ]
